// Generated by Wrangler on Mon Aug 12 2024 01:25:06 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	MY_KV_NAMESPACE: KVNamespace;
	BUCKET_NAME: "a1d-rb";
	EXPIRATION_TTL: 3600;
	ACCOUNT_ID: string;
	API_TOKEN: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	AWS_REGION: string;
	AWS_SQS_QUEUE_URL: string;
	JWT_SECRET: string;
	ADMIN_TOKEN: string;
	CANVA_APP_IDS: string;
	TASK_STATUS_DURABLE_OBJECT: DurableObjectNamespace;
	MY_BUCKET: R2Bucket;
	BILLING: AnalyticsEngineDataset;
	AI: Ai;
}
